# Generated by Django 4.1.7 on 2023-03-25 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='type',
            new_name='format',
        ),
    ]
