# Generated by Django 4.1.7 on 2023-03-25 22:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_type_image_format'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='size',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
