# Generated by Django 4.1.7 on 2023-03-25 22:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_image_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='size',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
