# Generated by Django 4.1.7 on 2023-03-25 23:08

import core.models
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_image_size'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resized',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resized', models.ImageField(upload_to=core.models.image_file_path, validators=[django.core.validators.validate_image_file_extension])),
                ('width', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('height', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('size', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.image')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
