# Generated by Django 4.1.7 on 2023-03-26 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_resized_quality'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resized',
            old_name='resized',
            new_name='resized_image',
        ),
    ]
